### ISSUE TITLE
Serialize DeferredResult

### ISSUE THREAD

**Issue by alexandermakeev** [FasterXML/jackson-datatype-hibernate#110]
Hello,

I have Spring REST API and I'm using asynchronious endpoints via DeferredResult:

```java
@RestController
public class TestController {

    @GetMapping
    public DeferredResult<List<Test>> getList() {
        return executor.execute(() -> service.getList());
    }

}
```

I'm getting com.fasterxml.jackson.databind.JsonMappingException: could not initialize proxy - no Session. Please help.

**Comment by cowtowncoder** [comment]
@alexandermakeev Usage questions belong to mailing lists, not issue tracker:

https://groups.google.com/forum/#!forum/jackson-user

especially since this does not appear to be related to Hibernate module.

However, I suspect this might even be more of a Spring REST question; however, Jackson user mailing list probably has spring users that might be able to help.
