### ISSUE TITLE
Release policy

### ISSUE THREAD

**Issue by dermot-hardy** [FasterXML/jackson-datatype-hibernate#133]
What is the idea of the 2.10.0.pr releases?  Is there a planned date for the official 2.10.0 release?

(Apologies if this is documented somewhere.  I did look for it but I couldn't find it.)

**Comment by cowtowncoder** [comment]
Pre-releases are meant to allow easier pre-release testing of upcoming minor versions, compared to SNAPSHOT builds, as there is a consistent set of versions.
My choice of suffix `pr` seems unfortunate in retrospect since while there is no real standard (AFAIK) on version qualifiers, apparently many tools would recognize `rc` and possible `alpha`, `beta` as "not release". But not `pr`.
