### ISSUE TITLE
an exception

### ISSUE THREAD

**Issue by finesoft** [FasterXML/jackson-datatype-hibernate#26]
hi guys

When use module-hibernate3 then throw an exception,Can someone help me

com.fasterxml.jackson.databind.JsonMappingException: Failed to instantiate standard serializer (of type com.fasterxml.jackson.databind.ser.std.NullSerializer): Class com.fasterxml.jackson.databind.ser.BasicSerializerFactory can not access a member of class com.fasterxml.jackson.databind.ser.std.NullSerializer with modifiers "private";the exceprion was at  items  serialization。

jackson-databind 2.2

My domain code:

public class Order{
    private String id;
    private String name;
    private Set<Item> items;
    //gettter... setter
}

public class Item{
    private String id;
    private String name;
    private String remark;
   //gettter... setter
}

**Comment by ohnooo** [comment]
I experience the same problem.

The data saves to the database but on my HTML console i get 500(internal server error) and on my compiler I get 

Servlet.service() for servlet [app-dispatcher] in context with path [/UNI-JSON] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: Failed to instantiate standard serializer (of type com.fasterxml.jackson.databind.ser.std.NullSerializer): Class com.fasterxml.jackson.databind.ser.BasicSerializerFactory can not access a member of class com.fasterxml.jackson.databind.ser.std.NullSerializer with modifiers "private"] with root cause
java.lang.IllegalAccessException: Class com.fasterxml.jackson.databind.ser.BasicSerializerFactory can not access a member of class com.fasterxml.jackson.databind.ser.std.NullSerializer with modifiers "private"


Spring frame work

pem.xml

```
  		<groupId>org.codehaus.jackson</groupId>
  		<artifactId>jackson-mapper-asl</artifactId>
  		<version>1.9.13</version>

  		<groupId>org.codehaus.jackson</groupId>
  		<artifactId>jackson-core-asl</artifactId>
  		<version>1.9.13</version>

  		<groupId>com.fasterxml.jackson.core</groupId>
  		<artifactId>jackson-databind</artifactId>
  		<version>2.2.3</version>

  		<groupId>mysql</groupId>
  		<artifactId>mysql-connector-java</artifactId>
  		<version>5.1.39</version>

  		<groupId>com.zaxxer</groupId>
  		<artifactId>HikariCP</artifactId>
  		<version>2.4.7</version>

  		<groupId>org.hibernate</groupId>
  		<artifactId>hibernate-core</artifactId>
  		<version>4.3.11.Final</version>
  
```

DAO

```
@Repository
@Transactional
@Component("bookDao")
public class BookDao {

     @Autowired
	private SessionFactory sessionFactory;

     public Session session(){
		return sessionFactory.getCurrentSession();
	}

     public void saveOrUpdate(Book book){
		session().saveOrUpdate(book);
	}

```



Controller
```
@Controller
@RequestMapping(value="/spa")
public class spaController(){

     @Autowired
     private BookDao bookDao;

     @RequestMapping(path="/booklist/{id}, method=RequestMethod.PUT, produces="application/json")
     @RequestBody
     public void save(@PathVariable("id") Integer id, @RequestBody Book book){
           bookDao.saveOrUpdate(book);
     }
}
```

Maybe someone could point me in a direction?  thank you

**Comment by cowtowncoder** [comment]
@ohnoo You have an ancient version of Jackson 2.x and you need to upgrade that.

**Comment by ohnooo** [comment]
@cowtowncoder oh wow thanks for the quick response.... and YES.... sorry... my problem
