### ISSUE TITLE
Does Jackson support hibenate 5 and Spring 4 combination?

### ISSUE THREAD

**Issue by amolskh** [FasterXML/jackson-datatype-hibernate#88]
I am using Hibernate5Module with Spring 4+ and hibernate .. 
I have configured MessageConvertor and ObjectMapped but still dosent seem to work

**Comment by yorl1n** [comment]
Hi, did you register H5M or H4M in ObjectMapper? 
I'm asking while I'm using hibernate 5 in conjuction with spring 4 and it works perfectly for me.

**Comment by cowtowncoder** [comment]
@amolskh In future, please use mailing lists for usage questions (including general applicability).
And since this is related to use via Spring, it may be useful to ask Spring forums too, although it may be difficult to figure out how responsibilities are split.

Hibernate 5 is supports, as long as you use hibernate5 module (as per @yorl1n 's suggestion).
Jackson does not know anything about Spring, but I am not aware of specific problems Spring 4 might have wrt modules.
